server:
  port:

info:
  app:
    name: ScrumFlow
    description: Sistema de Gerenciamento de Scrum
    version: 1.0.0

spring:
  application:
    name: ScrumFlow
  datasource:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    enabled: true
    user:
    password:

api:
  security:
    token_secret:
      
info:
  app:
    name:
    description: