server:
  port: 9010

spring:
  application:
    name: ScrumFlow
  datasource:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: validate
api:
  security:
    token_secret:
