CREATE TABLE user
(
    id BIGINT AUTO_INCREMENT NOT NULL,
    name VARCHAR( 100 ) NOT NULL,
    email VARCHAR( 80 ) NOT NULL UNIQUE,
    password VARCHAR( 255 ) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    active boolean NOT NULL,
    PRIMARY KEY ( id )
); 